server:
  port: 9070
spring:
  application:
    name: player-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/casino_dev
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

app:
  jwt-player-expiration-in-ms: 86400000
  jwt-player-refresh-expiration-in-ms: 86400000
  base-url-admin: http://localhost:4200
  swagger-enabled: true
  enum-package-name: com.casino.enums
  kafka-consumer-bootstrap-servers: b-2.kafka.1m2sc4.c25.kafka.us-east-1.amazonaws.com:9092,b-3.kafka.1m2sc4.c25.kafka.us-east-1.amazonaws.com:9092,b-1.kafka.1m2sc4.c25.kafka.us-east-1.amazonaws.com:9092
  kafka-email-topic-name: email_notification
  kafka-phone-verification-topic-name: phone_verification
  otp-max-retry-attempts: 3
  otp_expiration-in-ms: 300000
  skrill-account-id: 180655636
  skrill-pay-to-email: aakash.patel@ombpmllp.com
  skrill-merchant-apimqi-password-md5: 9de83881cc9eb0b8ecce1d7bec661649
  skrill-status-url: http://localhost:9004/v1/payment/skrill/status
  skrill-quick-checkout-url: https://pay.skrill.com/app/?sid=
  skrill-quick-withdraw-url: https://www.skrill.com/app/pay.pl
  stripe-secret-apikey: sk_test_51KmBS5K8RXJpc26GJGks8OOhuzqDhJ7O3XrfmRhVScyuRqgt0x5UtS0N3sTLHqXCXDZpSRIMBAfhK0oeKBHkRt8Q00JqVTTRAj
  stripe-public-apikey: pk_test_51KmBS5K8RXJpc26GU85GqUICFK9ZFr9dqILb1bkktmoKx4Z9bZumMQGResXEc8fmx8iaRzLnsGbkqyR10S4btxs200IRr2oyVU
  payment-min-transter-amount: 1

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
